server:
  port: 8001

spring:
  application:
    name: mcsv-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: mcsv-bike
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/biks/**
        - id: mcsv-car
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/cars/**
        - id: mcsv-user
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**

eureka:
  client:
    register-with-eureka: false
